apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acr-gateway-pdb
  namespace: acr-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acr-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acr-killswitch-pdb
  namespace: acr-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acr-killswitch
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acr-opa-pdb
  namespace: acr-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acr-opa
